### ISSUE TITLE
Puntos de Chequeo (checkpoint)

### ISSUE THREAD

**Issue by caaledcarre** [wilmar-arcila/Unity_clase_desarrollo_basico#11]
Realizar un Punto de chequeo donde durante una partida nuestro progreso quede guardado de forma permanente o temporal, permitiendo comenzar desde ese lugar o tiempo si llegamos a morir en el nivel.
![Captura](https://github.com/wilmar-arcila/Unity_clase_desarrollo_basico/assets/90487078/5bc35e51-654b-4e43-9f7a-e43d6196ef56)
![Captura3](https://github.com/wilmar-arcila/Unity_clase_desarrollo_basico/assets/90487078/ed1bcca3-7560-4bc9-905d-7368e91b6cca)

**Comment by wilmar-arcila** [comment]
Implementado en el _commit_ https://github.com/wilmar-arcila/Unity_clase_desarrollo_basico/commit/50380bb570034265ba51c853241c6d1800327220 de la rama **_develop_**
