### ISSUE TITLE
Niveles Ocultos

### ISSUE THREAD

**Issue by caaledcarre** [wilmar-arcila/Unity_clase_desarrollo_basico#15]
Permitir que el personaje mantenga su estado entre su cambio de escena cuando hay niveles ocultos. 
![Capturaniveloculto](https://github.com/wilmar-arcila/Unity_clase_desarrollo_basico/assets/90487078/ba68844f-7837-405a-92bc-0f6320104df6)
![Capturaniveloculto2](https://github.com/wilmar-arcila/Unity_clase_desarrollo_basico/assets/90487078/0a7087ef-602a-4833-b1c5-e036418e82c2)

**Comment by wilmar-arcila** [comment]
## Funcionalidad ya implementada.
Para teletransportarse entre diferentes puntos de una misma escena se puede utilizar el _InternalTeleporterController_ (implementado en el juego como la copa azul) y las estadísticas del personaje se mantienen por defecto entre las diferentes escenas.
