### ISSUE TITLE
Seleccionar personaje 

### ISSUE THREAD

**Issue by dpcarranzag** [wilmar-arcila/Unity_clase_desarrollo_basico#19]
Seleccion de personaje en el menú opciones

**Comment by wilmar-arcila** [comment]
[Tutorial](https://youtu.be/-3XGVie_SxM)  

[Para tener en cuenta](https://irfanbaysal.medium.com/instantiate-vs-prefabutility-instantiateprefab-747f43b5d717)  

Se hace uso del almacenamiento de preferencias de usuario en Unity, [PlayerPrefs](https://docs.unity3d.com/ScriptReference/PlayerPrefs.html), para almacenar **la selección** de personaje del jugador. Esta información será persistente entre sesiones.  

También se hace uso de los contenedores de datos [ScriptableObject](https://docs.unity3d.com/Manual/class-ScriptableObject.html), los cuales serán usados para almacenar la información de los diferentes personajes.

**Comment by dpcarranzag** [comment]
Buenos días profe
Gracias por la información

**Comment by wilmar-arcila** [comment]
Iniciando implementación

**Comment by wilmar-arcila** [comment]
Es necesario implementar el patrón [**Observer**](https://unity.com/how-to/create-modular-and-maintainable-code-observer-pattern) para desacoplar las mecánicas del personaje, las cuales pueden estar incluídas en su _prefab_, de su interacción con cada escena. Esto permitirá la instanciación del personaje seleccionado en [_Tiempo de ejecución_](https://es.wikipedia.org/wiki/Tiempo_de_ejecuci%C3%B3n) sin caer en el problema de dependencias.

**Comment by wilmar-arcila** [comment]
Patrón **Observer** implementado en la rama _develop_ en el commit https://github.com/wilmar-arcila/Unity_clase_desarrollo_basico/commit/01b21f0c528cfe598ad1f6215028894680083e16 y unida con esta rama.  

**InteractionEngine** (Publisher)  
 |-----------------------------------------------> CharacterStatsManager (Subscriber)  
 |-----------------------------------------------> CharacterController (Subscriber)  

**CharacterStatsmanager** (Publisher)  
 |-----------------------------------------------> StatsController (Subscriber)

**Comment by wilmar-arcila** [comment]
Funcionalidad implementada
