### ISSUE TITLE
Plataforma trampolin

### ISSUE THREAD

**Issue by HiddenGhostv1** [wilmar-arcila/Unity_clase_desarrollo_basico#21]
Es deseable que se implemente la función de trampolín, junto con la animación, gracias. 

![image](https://github.com/wilmar-arcila/Unity_clase_desarrollo_basico/assets/137956054/4c664ae8-5637-4367-8b3c-111b3d493692)

**Comment by wilmar-arcila** [comment]
Puede implementarse con cualquiera de las siguientes estrategias:
- Añadir al trampolin un [PhysicsMaterial2D](https://docs.unity3d.com/Manual/class-PhysicsMaterial2D.html)
- Añadir un _trigger_ al trampolin que desencadene la animación y que imprima una fuerza ascendente al personaje  

Se implementará con la segunda opción.

**Comment by wilmar-arcila** [comment]
Incluído en el _commit_ https://github.com/wilmar-arcila/Unity_clase_desarrollo_basico/commit/fd865ac6ce55d7bab314b95b9f8268b348ef85a5 de la rama _**develop**_
